//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBlog1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PostSet
    {

        public int PostId { get; set; }
        [Display(Name ="Chủ đề")]
		[Required]

		public string Title { get; set; }
        [Display(Name ="Nội dung")]
		[Required]

		public string Content { get; set; }
		[Display(Name = "Blog ID")]
        [Required]
		public int BlogBlogId { get; set; }
    
        public virtual BlogSet BlogSet { get; set; }
    }
}
